#!/bin/bash

# MSVC environment stolen from /msvc/VC/bin/bin/vcvars32.bat
# (To get the values from the vcvars script, run vcvars32.bat in a DOS prompt and then `set` to see what it defined)
export INCLUDE=/msvc/VC/INCLUDE:/msvc/VC/ATLMFC/INCLUDE:/wkits/8.0/include/shared:/wkits/8.0/include/um:/wkits/8.0/include/winrt:
export PATH="$PATH:/msvc/Common7/IDE/CommonExtensions/Microsoft/TestWindow:/msdk/F#/3.0/Framework/v4.0/:/msvc/Common7/IDE/:/msvc/VC/BIN:/msvc/Common7/Tools:/c/windows/Microsoft.NET/Framework/v4.0.30319:/c/windows/Microsoft.NET/Framework/v3.5:/msvc/VC/VCPackages:/msvc/Team Tools/Performance Tools:/wkits/8.0/bin/x86:/msdk/Windows/v8.0A/bin/NETFX 4.0 Tools:/msdk/Windows/v7.0A/Bin/:/c/windows/system32:/c/windows:/c/windows/System32/Wbem:/wkits/8.0/Windows Performance Toolkit/"
export LIB=/msvc/VC/LIB:/msvc/VC/ATLMFC/LIB:/wkits/8.0/lib/win8/um/x86:
export LIBPATH=/c/windows/Microsoft.NET/Framework/v4.0.30319:/c/windows/Microsoft.NET/Framework/v3.5:/msvc/VC/LIB:/msvc/VC/ATLMFC/LIB:/wkits/8.0/References/CommonConfiguration/Neutral:/msdk/Windows/v8.0/ExtensionSDKs/Microsoft.VCLibs/11.0/References/CommonConfiguration/neutral:

export MSVC_ENV=32
export WINDBG=/debug86/windbg.exe
export CDB=/debug86/cdb.exe


